package ru.detmir.hybris.common;

import java.lang.reflect.InvocationTargetException;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "CommonKafkaMessageRequest_In", targetNamespace = "urn:DetMir.ru:Hybris:Common")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface CommonKafkaMessageRequestIn {

  /**
   * Java representation of web method [CommonKafkaMessageRequest_In].
   */
  @javax.jws.WebMethod(operationName = "CommonKafkaMessageRequest_In", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.Oneway
  public void commonKafkaMessageRequestIn(@javax.jws.WebParam(name = "CommonKafkaMessageRequest", targetNamespace = "urn:DetMir.ru:Hybris:Common", partName = "CommonKafkaMessageRequest") ru.detmir.hybris.common.CommonKafkaMessageRequest commonKafkaMessageRequest);

}
